
export interface UniversityData {
  id: number | string;
  name: string;
  location: string;
  established: number | string;
  tuition_fee_rub: number;
  hostel_fee_rub: number;
  total_fee_rub: number;
  duration: string;
  indian_mess: boolean;
  ranking: string;
  notes: string;
  website?: string;
}

export const DETAILED_UNIVERSITIES: UniversityData[] = [
  // --- ORIGINAL LIST (1-38) ---
  {
    "id": 1,
    "name": "First Moscow State Medical University (Sechenov)",
    "location": "Moscow, Russia",
    "established": 1758,
    "tuition_fee_rub": 850000,
    "hostel_fee_rub": 110000,
    "total_fee_rub": 960000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "#1 in Russia",
    "notes": "The oldest and most prestigious medical university in Russia. Located in the capital."
  },
  {
    "id": 2,
    "name": "Pirogov Russian National Research Medical University",
    "location": "Moscow, Russia",
    "established": 1906,
    "tuition_fee_rub": 500000,
    "hostel_fee_rub": 28000,
    "total_fee_rub": 528000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 3 in Russia",
    "notes": "Fully English medium. Known for strict academics and high FMGE passing rates."
  },
  {
    "id": 3,
    "name": "Kazan Federal University (KFU)",
    "location": "Kazan, Russia",
    "established": 1804,
    "tuition_fee_rub": 540000,
    "hostel_fee_rub": 15000,
    "total_fee_rub": 555000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 20 in Russia",
    "notes": "Federal status university. Very modern campus (Universiade Village)."
  },
  {
    "id": 4,
    "name": "Bashkir State Medical University",
    "location": "Ufa, Russia",
    "established": 1932,
    "tuition_fee_rub": 399000,
    "hostel_fee_rub": 18000,
    "total_fee_rub": 417000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Ranked 136th",
    "notes": "Very popular among Indians (1000+ students). Direct flights often available."
  },
  {
    "id": 5,
    "name": "Crimea Federal University",
    "location": "Simferopol, Crimea",
    "established": 1918,
    "tuition_fee_rub": 315000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 350000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Ranked 197th",
    "notes": "Extremely low cost. Warm climate. Large Indian community."
  },
  {
    "id": 6,
    "name": "Far Eastern Federal University",
    "location": "Vladivostok, Russia",
    "established": 1899,
    "tuition_fee_rub": 495000,
    "hostel_fee_rub": 40000,
    "total_fee_rub": 535000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "QS World Ranked",
    "notes": "Smart campus on an island. High-tech infrastructure. Near Pacific Ocean."
  },
  {
    "id": 7,
    "name": "Orel State University",
    "location": "Orel, Russia",
    "established": 1931,
    "tuition_fee_rub": 317000,
    "hostel_fee_rub": 16000,
    "total_fee_rub": 333000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Ranked 183rd",
    "notes": "Budget-friendly option. Good for students seeking low cost."
  },
  {
    "id": 8,
    "name": "Kursk State Medical University",
    "location": "Kursk, Russia",
    "established": 1935,
    "tuition_fee_rub": 520000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 555000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 100",
    "notes": "First university to start English medium in Russia. Very experienced faculty."
  },
  {
    "id": 9,
    "name": "Tver State Medical University",
    "location": "Tver, Russia",
    "established": 1936,
    "tuition_fee_rub": 280500,
    "hostel_fee_rub": 18000,
    "total_fee_rub": 298500,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50 Medical",
    "notes": "Very close to Moscow (2 hours by train). Affordable fees."
  },
  {
    "id": 10,
    "name": "Smolensk State Medical University",
    "location": "Smolensk, Russia",
    "established": 1920,
    "tuition_fee_rub": 495000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 520000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 30 Medical",
    "notes": "Known for safety and good FMGE results. 4 hours from Moscow."
  },
  {
    "id": 11,
    "name": "People's Friendship University (RUDN)",
    "location": "Moscow, Russia",
    "established": 1960,
    "tuition_fee_rub": 830000,
    "hostel_fee_rub": 90000,
    "total_fee_rub": 920000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "QS World Ranked",
    "notes": "Most international university. Students from 150+ countries."
  },
  {
    "id": 12,
    "name": "Kazan State Medical University",
    "location": "Kazan, Russia",
    "established": 1814,
    "tuition_fee_rub": 475000,
    "hostel_fee_rub": 20000,
    "total_fee_rub": 495000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 10 Medical",
    "notes": "Separate from KFU. Dedicated purely to medicine. Very strict."
  },
  {
    "id": 13,
    "name": "Northern State Medical University",
    "location": "Arkhangelsk, Russia",
    "established": 1932,
    "tuition_fee_rub": 540000,
    "hostel_fee_rub": 45000,
    "total_fee_rub": 585000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 100",
    "notes": "Located in North Russia (very cold winters). Excellent academics."
  },
  {
    "id": 14,
    "name": "Orenburg State Medical University",
    "location": "Orenburg, Russia",
    "established": 1944,
    "tuition_fee_rub": 450000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 475000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top Regional",
    "notes": "Focus on practical training. Good Indian community."
  },
  {
    "id": 15,
    "name": "Perm State Medical University",
    "location": "Perm, Russia",
    "established": 1916,
    "tuition_fee_rub": 495000,
    "hostel_fee_rub": 30000,
    "total_fee_rub": 525000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 20 Medical",
    "notes": "Holds biggest patent portfolio in region. Good clinical exposure."
  },
  {
    "id": 16,
    "name": "Mari State University",
    "location": "Yoshkar-Ola, Russia",
    "established": 1972,
    "tuition_fee_rub": 365000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 390000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Emerging Top",
    "notes": "Rapidly growing popularity. Very clean and safe city (European style)."
  },
  {
    "id": 17,
    "name": "Volgograd State Medical University",
    "location": "Volgograd, Russia",
    "established": 1935,
    "tuition_fee_rub": 465000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 500000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 20 Medical",
    "notes": "Located in a historic city (Stalingrad). Very experienced with foreign students."
  },
  {
    "id": 18,
    "name": "Ryazan State Medical University",
    "location": "Ryazan, Russia",
    "established": 1943,
    "tuition_fee_rub": 360000,
    "hostel_fee_rub": 45000,
    "total_fee_rub": 405000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50",
    "notes": "Close to Moscow. Good balance of fee and quality."
  },
  {
    "id": 19,
    "name": "Altai State Medical University",
    "location": "Barnaul, Russia",
    "established": 1954,
    "tuition_fee_rub": 323600,
    "hostel_fee_rub": 20000,
    "total_fee_rub": 343600,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top Siberian",
    "notes": "Low fee structure. Located in Siberia (cold climate)."
  },
  {
    "id": 20,
    "name": "Kemerovo State Medical University",
    "location": "Kemerovo, Russia",
    "established": 1955,
    "tuition_fee_rub": 295000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 320000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Regional Leader",
    "notes": "One of the most affordable options in 2025."
  },
  {
    "id": 21,
    "name": "Kabardino Balkarian State University",
    "location": "Nalchik, Russia",
    "established": 1957,
    "tuition_fee_rub": 245500,
    "hostel_fee_rub": 15000,
    "total_fee_rub": 260500,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Budget Choice",
    "notes": "Lowest fee structure on this list. Located in Caucasus mountains region."
  },
  {
    "id": 22,
    "name": "Yaroslavl State Medical University",
    "location": "Yaroslavl, Russia",
    "established": 1944,
    "tuition_fee_rub": 262750,
    "hostel_fee_rub": 55000,
    "total_fee_rub": 317750,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Golden Ring",
    "notes": "Located in the 'Golden Ring' of Russia. Historic and beautiful city."
  },
  // Skipped ID 23 (Omsk) here, using the updated data at ID 37
  {
    "id": 24,
    "name": "Pskov State University",
    "location": "Pskov, Russia",
    "established": 2010,
    "tuition_fee_rub": 240000,
    "hostel_fee_rub": 10000,
    "total_fee_rub": 250000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Modern",
    "notes": "Very cheap tuition. Near the border of Estonia (EU)."
  },
  {
    "id": 25,
    "name": "Dagestan State Medical University",
    "location": "Makhachkala, Russia",
    "established": 1932,
    "tuition_fee_rub": 280000,
    "hostel_fee_rub": 18000,
    "total_fee_rub": 298000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Regional",
    "notes": "Warm climate near Caspian Sea. Good infrastructure."
  },
  {
    "id": 26,
    "name": "Amur State Medical Academy",
    "location": "Blagoveshchensk, Russia",
    "established": 1952,
    "tuition_fee_rub": 280000,
    "hostel_fee_rub": 70000,
    "total_fee_rub": 350000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Regional Top",
    "notes": "Located in the Far East. Affordable fee structure."
  },
  {
    "id": 27,
    "name": "Astrakhan State Medical University",
    "location": "Astrakhan, Russia",
    "established": 1918,
    "tuition_fee_rub": 300000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 335000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 100",
    "notes": "One of the oldest medical universities. Very popular for its low cost of living."
  },
  {
    "id": 28,
    "name": "Belgorod State National Research University",
    "location": "Belgorod, Russia",
    "established": 1876,
    "tuition_fee_rub": 441000,
    "hostel_fee_rub": 90000,
    "total_fee_rub": 531000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "National Research University",
    "notes": "High-tech campus. Fees often pegged to USD ($4900/year approx)."
  },
  {
    "id": 29,
    "name": "Chuvash State University",
    "location": "Cheboksary, Russia",
    "established": 1967,
    "tuition_fee_rub": 240000,
    "hostel_fee_rub": 80000,
    "total_fee_rub": 320000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Regional Leader",
    "notes": "Very affordable tuition. City is located on the Volga River."
  },
  {
    "id": 30,
    "name": "Pavlov First Saint Petersburg State Medical University",
    "location": "St. Petersburg, Russia",
    "established": 1897,
    "tuition_fee_rub": 396000,
    "hostel_fee_rub": 45000,
    "total_fee_rub": 441000,
    "duration": "6 Years",
    "indian_mess": false,
    "ranking": "Top 5 in Russia",
    "notes": "Premium university. Strict academics. Located in the cultural capital."
  },
  {
    "id": 31,
    "name": "Saratov State Medical University",
    "location": "Saratov, Russia",
    "established": 1909,
    "tuition_fee_rub": 217000,
    "hostel_fee_rub": 50000,
    "total_fee_rub": 267000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50",
    "notes": "One of the lowest tuition fees in Russia (approx 2.17 Lakh RUB)."
  },
  {
    "id": 32,
    "name": "Stavropol State Medical University",
    "location": "Stavropol, Russia",
    "established": 1938,
    "tuition_fee_rub": 450000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 485000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top Regional",
    "notes": "Located in South Russia. Good climate and infrastructure."
  },
  {
    "id": 33,
    "name": "Tambov State University",
    "location": "Tambov, Russia",
    "established": 1918,
    "tuition_fee_rub": 350000,
    "hostel_fee_rub": 0,
    "total_fee_rub": 350000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 100",
    "notes": "Hostel fee is often included in the tuition package."
  },
  {
    "id": 34,
    "name": "Ulyanovsk State University",
    "location": "Ulyanovsk, Russia",
    "established": 1988,
    "tuition_fee_rub": 495000,
    "hostel_fee_rub": 36000,
    "total_fee_rub": 531000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "NMC Listed",
    "notes": "High FMGE passing rate. Fees approx $5500/year."
  },
  {
    "id": 35,
    "name": "Kuban State Medical University",
    "location": "Krasnodar, Russia",
    "established": 1920,
    "tuition_fee_rub": 482000,
    "hostel_fee_rub": 20000,
    "total_fee_rub": 502000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50",
    "notes": "Located near the Black Sea. Very pleasant climate."
  },
  {
    "id": 36,
    "name": "Kirov State Medical University",
    "location": "Kirov, Russia",
    "established": 1987,
    "tuition_fee_rub": 270000,
    "hostel_fee_rub": 60000,
    "total_fee_rub": 330000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Budget Choice",
    "notes": "Very affordable total package. Modern facilities."
  },
  {
    "id": 37,
    "name": "Omsk State Medical University",
    "location": "Omsk, Russia",
    "established": 1920,
    "tuition_fee_rub": 330000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 365000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top Siberian",
    "notes": "Strict academic standards. Good clinical exposure."
  },
  {
    "id": 38,
    "name": "Tyumen State Medical University",
    "location": "Tyumen, Russia",
    "established": 1963,
    "tuition_fee_rub": 450000,
    "hostel_fee_rub": 0,
    "total_fee_rub": 450000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Oil Capital",
    "notes": "Tuition often includes hostel. High standard of living in the city."
  },

  // --- UPDATED BATCH (Replacing duplicates with fresher data) ---
  {
    "id": 39, 
    "name": "North-Western State Medical University (Mechnikov)",
    "location": "St. Petersburg, Russia",
    "established": 2011,
    "tuition_fee_rub": 490000,
    "hostel_fee_rub": 36000,
    "total_fee_rub": 526000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 10",
    "notes": "Formed by merger of two major academies. Premium education quality."
  },
  {
    "id": 40, 
    "name": "Siberian State Medical University",
    "location": "Tomsk, Russia",
    "established": 1888,
    "tuition_fee_rub": 385600,
    "hostel_fee_rub": 70000,
    "total_fee_rub": 455600,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 3 Medical",
    "notes": "One of the only medical universities in Russia with 'National Research' status."
  },
  {
    "id": 41,
    "name": "Voronezh State Medical University",
    "location": "Voronezh, Russia",
    "established": 1918,
    "tuition_fee_rub": 385000,
    "hostel_fee_rub": 35000,
    "total_fee_rub": 420000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50",
    "notes": "Popular destination for international students. Close to Moscow."
  },
  {
    "id": 42,
    "name": "Rostov State Medical University",
    "location": "Rostov-on-Don, Russia",
    "established": 1930,
    "tuition_fee_rub": 365000,
    "hostel_fee_rub": 40000,
    "total_fee_rub": 405000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Southern Leader",
    "notes": "Largest medical university in South Russia. Cosmopolitan city."
  },
  {
    "id": 43,
    "name": "Samara State Medical University",
    "location": "Samara, Russia",
    "established": 1919,
    "tuition_fee_rub": 420000,
    "hostel_fee_rub": 30000,
    "total_fee_rub": 450000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Innovation Hub",
    "notes": "Known for IT in medicine and 3D anatomical modeling."
  },
  {
    "id": 44,
    "name": "Saint Petersburg State University",
    "location": "St. Petersburg, Russia",
    "established": 1724,
    "tuition_fee_rub": 560000,
    "hostel_fee_rub": 50000,
    "total_fee_rub": 610000,
    "duration": "6 Years",
    "indian_mess": false,
    "ranking": "#2 in Russia",
    "notes": "General university with a prestigious medical faculty. High entry requirements."
  },
  {
    "id": 45, 
    "name": "Privolzhsky Research Medical University",
    "location": "Nizhny Novgorod, Russia",
    "established": 1920,
    "tuition_fee_rub": 460000,
    "hostel_fee_rub": 15000,
    "total_fee_rub": 475000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Research Hub",
    "notes": "Known for high-tech medical research and burn treatment center."
  },
  {
    "id": 46, 
    "name": "Ural State Medical University",
    "location": "Yekaterinburg, Russia",
    "established": 1930,
    "tuition_fee_rub": 260000,
    "hostel_fee_rub": 12000,
    "total_fee_rub": 272000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Top 50",
    "notes": "Located in Russia's 4th largest city. Very high quality of life."
  },
  {
    "id": 47, 
    "name": "North Caucasian State Academy",
    "location": "Cherkessk, Russia",
    "established": 1938,
    "tuition_fee_rub": 332000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 357000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Budget Friendly",
    "notes": "Very affordable option in the Caucasus region."
  },
  {
    "id": 48, 
    "name": "Izhevsk State Medical Academy",
    "location": "Izhevsk, Russia",
    "established": 1933,
    "tuition_fee_rub": 400000,
    "hostel_fee_rub": 0,
    "total_fee_rub": 400000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Regional",
    "notes": "Hostel fee is often included in the package. Home of Kalashnikov."
  },
  {
    "id": 49, 
    "name": "Irkutsk State Medical University",
    "location": "Irkutsk, Russia",
    "established": 1919,
    "tuition_fee_rub": 360000,
    "hostel_fee_rub": 45000,
    "total_fee_rub": 405000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Siberian Top",
    "notes": "Near Lake Baikal (deepest lake in the world). Scenic location."
  },
  {
    "id": 50,
    "name": "Chechen State University",
    "location": "Grozny, Russia",
    "established": 1938,
    "tuition_fee_rub": 220000,
    "hostel_fee_rub": 30000,
    "total_fee_rub": 250000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Developing",
    "notes": "Very modern campus built recently. Extremely low tuition fees."
  },
  // --- NEW UNIQUE ENTRIES ---
  {
    "id": 51,
    "name": "Immanuel Kant Baltic Federal University",
    "location": "Kaliningrad, Russia",
    "established": 1947,
    "tuition_fee_rub": 305000,
    "hostel_fee_rub": 15000,
    "total_fee_rub": 320000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Federal Status",
    "notes": "Located in the European enclave of Russia (near Poland). Very European vibe."
  },
  {
    "id": 52,
    "name": "South Ural State Medical University",
    "location": "Chelyabinsk, Russia",
    "established": 1944,
    "tuition_fee_rub": 260000,
    "hostel_fee_rub": 20500,
    "total_fee_rub": 280500,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Budget Choice",
    "notes": "One of the most affordable tuition fees in the Urals region."
  },
  {
    "id": 53,
    "name": "Ivanovo State Medical Academy",
    "location": "Ivanovo, Russia",
    "established": 1930,
    "tuition_fee_rub": 260000,
    "hostel_fee_rub": 25000,
    "total_fee_rub": 285000,
    "duration": "6 Years",
    "indian_mess": true,
    "ranking": "Golden Ring",
    "notes": "Located close to Moscow. Famous for textile industry and student safety."
  }
];

// Generate simple list of names for dropdowns
export const RUSSIAN_UNIVERSITIES = DETAILED_UNIVERSITIES.map(u => u.name).sort();

export const getUniversityData = (name: string): UniversityData => {
  const found = DETAILED_UNIVERSITIES.find(u => u.name === name);
  if (found) return found;

  // Generic fallback if not found in list
  return {
    id: Math.random(),
    name: name,
    location: "Russia",
    established: "N/A",
    tuition_fee_rub: 0,
    hostel_fee_rub: 0,
    total_fee_rub: 0,
    duration: "6 Years",
    indian_mess: false,
    ranking: "Regional",
    notes: "Detailed fee structure pending update. Contact admin."
  };
};
